import selectprof from "../../images/cProfileImg.png";

const EmpAllCardData = [
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
    {
        selectprof: selectprof,
        selProfname: "Robert Downey",
        role: "Frontend Developer",
        companyName: "SOV Technologies",
        location: "Mumbai",
        noticeday: "15",
        skillOne: "HTML5",
        skillTwo: "CSS3",
        skillThree: "JavaScript", 
    },
]

export default EmpAllCardData;